from typing import List, Tuple
#structure is (title, developer, year, [characters], [genres])

game_db: List[Tuple[str, str, int, List[str], List[str]]] = [
    ("the legend of zelda: breath of the wild", "nintendo", 2017, ["link", "zelda", "ganon"], ["action-adventure", "open world"]),
    ("the witcher 3: wild hunt", "cd projekt red", 2015, ["geralt", "yennefer", "triss"], ["action RPG", "open world"]),
    ("god of war", "santa monica studio", 2018, ["kratos", "atreus"], ["action-adventure", "hack and slash"]),
    ("hollow knight", "team cherry", 2017, ["knight", "hornet"], ["metroidvania", "platformer"]),
    ("elden ring", "fromsoftware", 2022, ["tarnished", "melina", "radahn"], ["action RPG", "open world"]),
    ("red dead redemption 2", "rockstar games", 2018, ["arthur morgan", "dutch", "john marston"], ["action-adventure", "open world"]),
    ("the last of us", "naughty dog", 2013, ["joel", "ellie"], ["action-adventure", "survival horror"]),
    ("cyberpunk 2077", "cd projekt red", 2020, ["v", "johnny silverhand"], ["action RPG", "open world"]),
    ("portal 2", "valve", 2011, ["chell", "glados", "wheatley"], ["puzzle-platformer", "sci-fi"]),
    ("minecraft", "mojang", 2011, ["steve", "alex"], ["sandbox", "survival", "creative"]),
    ("super mario odyssey", "nintendo", 2017, ["mario", "cappy", "bowser"], ["platformer", "adventure"]),
    ("metal gear solid v: the phantom pain", "konami", 2015, ["big boss", "quiet", "ocelot"], ["stealth", "action-adventure"]),
    ("persona 5", "atlus", 2016, ["joker", "morgana", "ann", "ryuji"], ["JRPG", "social simulation"]),
    ("bioshock infinite", "irrational games", 2013, ["booker dewitt", "elizabeth"], ["first-person shooter", "sci-fi"]),
    ("undertale", "toby fox", 2015, ["frisk", "sans", "papyrus", "toriel"], ["RPG", "indie"]),
    ("mass effect 2", "bioware", 2010, ["commander shepard", "garrus", "liara"], ["action RPG", "sci-fi"]),
    ("half-life 2", "valve", 2004, ["gordon freeman", "alyx vance"], ["first-person shooter", "sci-fi"]),
    ("doom eternal", "id software", 2020, ["doom slayer", "vega", "khan maykr"], ["first-person shooter", "action"]),
    ("final fantasy vii", "square enix", 1997, ["cloud", "tifa", "aerith", "sephiroth"], ["JRPG", "fantasy"]),
    ("stardew valley", "concernedape", 2016, ["farmer", "sebastian", "abigail", "penny"], ["farming sim", "life sim", "RPG"]),
    ("the legend of zelda: tears of the kingdom", "nintendo", 2023, ["link", "zelda", "ganondorf"], ["action-adventure", "open world"]),
    ("god of war ragnarok", "santa monica studio", 2022, ["kratos", "atreus", "freya"], ["action-adventure", "hack and slash"]),
    ("the last of us part ii", "naughty dog", 2020, ["ellie", "abby", "joel"], ["action-adventure", "survival horror"]),
    ("red dead redemption", "rockstar games", 2010, ["john marston", "bonnie mcfarlane"], ["action-adventure", "open world"]),
    ("the witcher 2: assassins of kings", "cd projekt red", 2011, ["geralt", "triss", "roche"], ["action RPG", "fantasy"]),
    ("dark souls iii", "fromsoftware", 2016, ["ashen one", "fire keeper", "lothric"], ["action RPG", "soulslike"]),
    ("metal gear solid 3: snake eater", "konami", 2004, ["naked snake", "the boss", "ocelot"], ["stealth", "action-adventure"]),
    ("bioshock", "irrational games", 2007, ["jack", "atlas", "andrew ryan"], ["first-person shooter", "sci-fi", "horror"]),
    ("persona 4", "atlus", 2008, ["yu narukami", "yosuke", "chie", "teddie"], ["JRPG", "social simulation"]),
    ("half-life: alyx", "valve", 2020, ["alyx vance", "russell"], ["first-person shooter", "VR", "sci-fi"]),
    ("super mario bros.", "nintendo", 1985, ["mario", "luigi", "bowser"], ["platformer"]),
    ("super mario world", "nintendo", 1990, ["mario", "luigi", "yoshi"], ["platformer"]),
    ("super mario 64", "nintendo", 1996, ["mario", "bowser"], ["platformer", "3d platformer"]),
    ("super mario galaxy", "nintendo", 2007, ["mario", "rosalina"], ["platformer", "adventure"]),
    ("mario kart 8 deluxe", "nintendo", 2017, ["mario", "peach", "bowser"], ["racing", "party"]),
    ("the legend of zelda: ocarina of time", "nintendo", 1998, ["link", "zelda", "ganondorf"], ["action-adventure"]),
    ("the legend of zelda: a link to the past", "nintendo", 1991, ["link", "zelda", "ganon"], ["action-adventure"]),
    ("zelda: majoras mask", "nintendo", 2000, ["link", "zelda", "skull kid"], ["action-adventure"]),
    ("the legend of zelda: twilight princess", "nintendo", 2006, ["link", "midna", "ganondorf"], ["action-adventure"]),
    ("pokemon red", "game freak", 1996, ["player", "charizard", "mewtwo"], ["RPG", "monster catching"]),
    ("pokemon blue", "game freak", 1996, ["player", "squirtle", "mewtwo"], ["RPG", "monster catching"]),
    ("pokemon gold", "game freak", 1999, ["player", "ho-oh", "lugia"], ["RPG", "monster catching"]),
    ("pokemon silver", "game freak", 1999, ["player", "lugia", "ho-oh"], ["RPG", "monster catching"]),
    ("pokemon sword", "game freak", 2019, ["player", "zacian", "zacian"], ["RPG", "monster catching"]),
    ("pokemon shield", "game freak", 2019, ["player", "zamazenta"], ["RPG", "monster catching"]),
    ("pokemon go", "niantic", 2016, ["trainer"], ["AR", "mobile", "monster catching"]),
    ("animal crossing: new horizons", "nintendo", 2020, ["player", "tom nook", "isabelle"], ["life sim", "social sim"]),
    ("the sims 4", "maxis", 2014, ["sim"], ["life sim", "simulation"]),
    ("the sims 3", "maxis", 2009, ["sim"], ["life sim", "simulation"]),
    ("the sims", "maxis", 2000, ["sim"], ["life sim", "simulation"]),
    ("grand theft auto v", "rockstar north", 2013, ["michael", "trevor", "franklin"], ["action-adventure", "open world"]),
    ("grand theft auto: san andreas", "rockstar north", 2004, ["cj", "sweet"], ["action-adventure", "open world"]),
    ("grand theft auto iv", "rockstar north", 2008, ["niko bellic", "roman"], ["action-adventure", "open world"]),
    ("gta: vice city", "rockstar north", 2002, ["tommy vercetti"], ["action-adventure", "open world"]),
    ("gta iii", "rockstar north", 2001, ["claude"], ["action-adventure", "open world"]),
    ("bioshock 2", "2k marin", 2010, ["subject delta", "elisabeth"], ["first-person shooter", "sci-fi", "horror"]),
    ("dishonored", "arcane studios", 2012, ["corvo attano", "emily"], ["stealth", "action-adventure"]),
    ("dishonored 2", "arcane studios", 2016, ["emily k.", "corvo"], ["stealth", "action-adventure"]),
    ("dishonored: death of the outsider", "arcane studios", 2017, ["the outsider", "billy"], ["stealth", "action-adventure"]),
    ("dark souls", "fromsoftware", 2011, ["chosen undead"], ["action RPG", "soulslike"]),
    ("dark souls ii", "fromsoftware", 2014, ["heirs of the sun"], ["action RPG", "soulslike"]),
    ("bloodborne", "fromsoftware", 2015, ["hunter", "lady maria"], ["action RPG", "soulslike", "gothic"]),
    ("demon's souls", "fromsoftware", 2009, ["slayer"], ["action RPG", "soulslike"]),
    ("sekiro: shadows die twice", "fromsoftware", 2019, ["wolf", "genichiro"], ["action-adventure", "action"]),
    ("nioh", "team ninja", 2017, ["william", "yoshitsune"], ["action RPG", "soulslike"]),
    ("nioh 2", "team ninja", 2020, ["protagonist"], ["action RPG", "soulslike"]),
    ("monster hunter: world", "capcom", 2018, ["hunter", "palico"], ["action RPG", "hunt"]),
    ("monster hunter rise", "capcom", 2021, ["hunter", "palamute"], ["action RPG", "hunt"]),
    ("resident evil 2", "capcom", 1998, ["leon kennedy", "claire redfield"], ["survival horror"]),
    ("resident evil 4", "capcom", 2005, ["leon kennedy", "ada wong"], ["survival horror", "third-person shooter"]),
    ("resident evil 7: biohazard", "capcom", 2017, ["ethan winters", "mia"], ["survival horror", "first-person"]),
    ("resident evil village", "capcom", 2021, ["ethan winters", "lady dimitrescu"], ["survival horror"]),
    ("devil may cry 5", "capcom", 2019, ["dante", "nero", "vergil"], ["action", "hack and slash"]),
    ("dmc: devil may cry", "capcom", 2001, ["dante"], ["action", "hack and slash"]),
    ("bayonetta", "platinumgames", 2009, ["bayonetta"], ["action", "hack and slash"]),
    ("vanquish", "platinumgames", 2010, ["sam gideon"], ["third-person shooter", "action"]),
    ("astral chain", "platinumgames", 2019, ["officer"], ["action", "hack and slash", "sci-fi"]),
    ("nier: automata", "platinumgames", 2017, ["2b", "9s", "a2"], ["action RPG", "sci-fi"]),
    ("nier replicant", "square enix", 2021, ["protagonist", "emil"], ["action RPG", "fantasy"]),
    ("okami", "clover studio", 2006, ["amaterasu"], ["action-adventure", "mythic"]),
    ("shadow of the colossus", "team ijs", 2005, ["wander", "mono"], ["action-adventure", "puzzle"]),
    ("god of war (2005)", "santa monica studio", 2005, ["kratos"], ["action", "hack and slash"]),
    ("god of war ii", "santa monica studio", 2007, ["kratos"], ["action", "hack and slash"]),
    ("god of war iii", "santa monica studio", 2010, ["kratos"], ["action", "hack and slash"]),
    ("uncharted: nathan drake collection", "naughty dog", 2015, ["nathan drake", "sully"], ["action-adventure"]),
    ("uncharted 2: among thieves", "naughty dog", 2009, ["nathan drake", "sully"], ["action-adventure"]),
    ("uncharted 4: a thief's end", "naughty dog", 2016, ["nathan drake", "sully"], ["action-adventure"]),
    ("the last guardian", "genDesign", 2016, ["boy", "trico"], ["action-adventure", "puzzle"]),
    ("shadow of mordor", "monolith productions", 2014, ["talion", "celebrimbor"], ["action-adventure", "open world"]),
    ("shadow of war", "monolith productions", 2017, ["talion"], ["action-adventure", "open world"]),
    ("assassin's creed", "ubisoft montreal", 2007, ["altair", "ezio"], ["stealth", "action-adventure"]),
    ("assassin's creed ii", "ubisoft montreal", 2009, ["ezio auditore"], ["stealth", "action-adventure"]),
    ("assassin's creed brotherhood", "ubisoft roma", 2010, ["ezio", "cesare borgia"], ["stealth", "action-adventure"]),
    ("assassin's creed iv: black flag", "ubisoft montreal", 2013, ["edward kenway"], ["action-adventure", "open world"]),
    ("assassin's creed odyssey", "ubisoft", 2018, ["alexios", "kassandra"], ["action RPG", "open world"]),
    ("assassin's creed origins", "ubisoft", 2017, ["bayek"], ["action-adventure", "open world"]),
    ("assassin's creed valhalla", "ubisoft", 2020, ["eivor"], ["action RPG", "open world"]),
    ("far cry 3", "ubisoft montreal", 2012, ["jason brody", "vaas"], ["first-person shooter", "open world"]),
    ("far cry 4", "ubisoft", 2014, ["ajay ghale"], ["first-person shooter", "open world"]),
    ("far cry 5", "ubisoft", 2018, ["rookie"], ["first-person shooter", "open world"]),
    ("far cry primal", "ubisoft", 2016, ["takkar"], ["action-adventure", "survival"]),
    ("metro 2033", "4a games", 2010, ["artem"], ["first-person shooter", "post-apocalyptic"]),
    ("metro: last light", "4a games", 2013, ["artem"], ["first-person shooter", "post-apocalyptic"]),
    ("metro exodus", "4a games", 2019, ["arloy? (narrative)"], ["first-person shooter", "open world"]),
    ("the elder scrolls v: skyrim", "bethesda game studios", 2011, ["dragonborn"], ["RPG", "open world"]),
    ("the elder scrolls iv: oblivion", "bethesda game studios", 2006, ["player"], ["RPG", "open world"]),
    ("the elder scrolls iii: morrowind", "bethesda", 2002, ["player"], ["RPG"]),
    ("fallout 3", "bethesda game studios", 2008, ["lone wanderer"], ["RPG", "post-apocalyptic"]),
    ("fallout: new vegas", "obsidian", 2010, ["courier"], ["RPG", "post-apocalyptic"]),
    ("fallout 4", "bethesda game studios", 2015, ["sole survivor"], ["RPG", "open world"]),
    ("fallout 76", "bethesda game studios", 2018, ["player"], ["MMO", "open world"]),
    ("portal", "valve", 2007, ["chell", "glados"], ["puzzle-platformer", "sci-fi"]),
    ("left 4 dead", "valve", 2008, ["zoey", "bill"], ["co-op", "survival horror"]),
    ("left 4 dead 2", "valve", 2009, ["coach", "ellis"], ["co-op", "survival horror"]),
    ("team fortress 2", "valve", 2007, ["scout", "soldier", "heavy"], ["multiplayer", "shooter"]),
    ("counter-strike: global offensive", "valve", 2012, ["terrorist", "counter-terrorist"], ["first-person shooter", "competitive"]),
    ("counter-strike 1.6", "valve", 1999, ["terrorist", "counter-terrorist"], ["first-person shooter", "competitive"]),
    ("half-life", "valve", 1998, ["gordon freeman"], ["first-person shooter", "sci-fi"]),
    ("quake", "id software", 1996, ["ranger"], ["first-person shooter"]),
    ("quake ii", "id software", 1997, ["marine"], ["first-person shooter"]),
    ("wolfenstein: the new order", "machinegames", 2014, ["b.j. blazkowicz"], ["first-person shooter", "alternate history"]),
    ("wolfenstein ii: the new colossus", "machinegames", 2017, ["b.j. blazkowicz"], ["first-person shooter", "alternate history"]),
    ("call of duty 4: modern warfare", "infinity ward", 2007, ["captain price", "soap"], ["first-person shooter", "military"]),
    ("call of duty: modern warfare 2", "infinity ward", 2009, ["rover? (characters)"], ["first-person shooter", "military"]),
    ("call of duty: modern warfare (2019)", "infinity ward", 2019, ["captain price"], ["first-person shooter", "military"]),
    ("call of duty: black ops", "treyarch", 2010, ["alex mason"], ["first-person shooter", "military"]),
    ("call of duty: black ops ii", "treyarch", 2012, ["david mason"], ["first-person shooter", "military"]),
    ("call of duty: warzone", "infinity ward", 2020, ["player"], ["battle royale", "multiplayer"]),
    ("battlefield 1", "DICE", 2016, ["soldier"], ["first-person shooter", "historical"]),
    ("battlefield 4", "DICE", 2013, ["soldier"], ["first-person shooter", "multiplayer"]),
    ("overwatch", "blizzard entertainment", 2016, ["tracer", "mercy"], ["hero shooter", "multiplayer"]),
    ("overwatch 2", "blizzard entertainment", 2022, ["soldier 76", "tracer"], ["hero shooter", "multiplayer"]),
    ("diablo ii", "blizzard north", 2000, ["player", "deckard cain"], ["action RPG", "dark fantasy"]),
    ("diablo iii", "blizzard entertainment", 2012, ["player", "reaper of souls"], ["action RPG"]),
    ("starcraft", "blizzard entertainment", 1998, ["jim raynor", "kerrigan"], ["RTS", "sci-fi"]),
    ("starcraft ii: wings of liberty", "blizzard entertainment", 2010, ["jim raynor"], ["RTS", "sci-fi"]),
    ("hearthstone", "blizzard entertainment", 2014, ["mage", "warrior"], ["card game", "online"]),
    ("warcraft iii: reign of chaos", "blizzard entertainment", 2002, ["arthas", "jaina"], ["RTS", "fantasy"]),
    ("warcraft iii: reforged", "blizzard entertainment", 2020, ["arthas"], ["RTS", "fantasy"]),
    ("star wars: knights of the old republic", "obsidian", 2003, ["revan", "bastila"], ["RPG", "sci-fi"]),
    ("star wars: knights of the old republic ii", "obsidian", 2004, ["revan?"], ["RPG", "sci-fi"]),
    ("lego star wars: the complete saga", "travellers tales", 2007, ["luke", "vader"], ["puzzle", "action", "family"]),
    ("lego marvel super heroes", "travellers tales", 2013, ["iron man", "spider-man"], ["action", "family"]),
    ("batman: arkham asylum", "rocksteady studios", 2009, ["batman", "joker"], ["action-adventure", "superhero"]),
    ("batman: arkham city", "rocksteady studios", 2011, ["batman", "catwoman"], ["action-adventure", "superhero"]),
    ("spider-man (ps4)", "insomniac games", 2018, ["peter parker", "miles morales"], ["action-adventure", "open world"]),
    ("spider-man: miles morales", "insomniac games", 2020, ["miles morales"], ["action-adventure", "open world"]),
    ("little big planet", "media molecule", 2008, ["sackboy"], ["platformer", "creative"]),
    ("little big planet 2", "media molecule", 2011, ["sackboy"], ["platformer", "creative"]),
    ("rocket league", "psyonix", 2015, ["player"], ["sports", "competitive"]),
    ("terraria", "re-logic", 2011, ["player"], ["sandbox", "action-adventure"]),
    ("factorio", "wube software", 2020, ["engineer"], ["simulation", "automation"]),
    ("celeste", "extremely OK games", 2018, ["madeline"], ["platformer", "indie"]),
    ("hades", "supergiant games", 2020, ["zagreus", "megaera"], ["roguelike", "action"]),
    ("transistor", "supergiant games", 2014, ["red"], ["RPG", "sci-fi"]),
    ("pyre", "supergiant games", 2017, ["rite leader"], ["RPG", "party"]),
    ("into the breach", "subset games", 2018, ["pilot"], ["strategy", "turn-based"]),
    ("faster than light", "subset games", 2012, ["captain"], ["roguelike", "strategy"]),
    ("hotline miami", "devolver digital", 2012, ["jacket"], ["action", "top-down"]),
    ("enter the gungeon", "dodge roll", 2016, ["pilot"], ["roguelike", "action"]),
    ("binding of isaac", "edmund mcmillen", 2011, ["isaac"], ["roguelike", "action"]),
    ("rogue legacy", "cellar door games", 2013, ["knight"], ["roguelike", "platformer"]),
    ("cuphead", "studio mdhr", 2017, ["cuphead", "mugman"], ["run and gun", "platformer"]),
    ("shovel knight", "yacht club games", 2014, ["shovel knight"], ["platformer", "indie"]),
    ("ghost of tsushima", "sucker punch productions", 2020, ["jin sakai"], ["action-adventure", "open world"]),
    ("kena: bridge of spirits", "ember labs", 2021, ["kena"], ["action-adventure", "indie"]),
    ("luigi's mansion 3", "next level games", 2019, ["luigi", "king boo"], ["puzzle", "adventure"]),
    ("metroid prime", "retro studios", 2002, ["samus aran"], ["first-person", "metroidvania"]),
    ("metroid prime 2: echoes", "retro studios", 2004, ["samus aran"], ["first-person", "metroidvania"]),
    ("metroid prime 3: coriolis", "retro studios", 2007, ["samus aran"], ["first-person", "metroidvania"]),
    ("metroid dread", "nintendo", 2021, ["samus aran"], ["metroidvania", "action"]),
    ("paper mario: the thousand-year door", "intelligent systems", 2004, ["mario", "peach"], ["RPG", "adventure"]),
    ("paper mario: origami king", "intelligent systems", 2020, ["mario"], ["RPG", "adventure"]),
    ("fire emblem: three houses", "intelligent systems", 2019, ["byleth", "eddard"], ["strategy RPG", "JRPG"]),
    ("fire emblem awakening", "intelligent systems", 2012, ["chrom", "lucina"], ["strategy RPG", "JRPG"]),
    ("xenoblade chronicles", "monolith soft", 2010, ["shulk", "fonse"], ["JRPG", "action"]),
    ("xenoblade chronicles 2", "monolith soft", 2017, ["pyra", "rex"], ["JRPG", "action"]),
    ("xenoblade chronicles 3", "monolith soft", 2022, ["taion", "mio"], ["JRPG", "action"]),
    ("chrono trigger", "square", 1995, ["cron o? (typo)"], ["JRPG"]),
    ("final fantasy vi", "square", 1994, ["terra", "locke", "kefka"], ["JRPG"]),
    ("final fantasy ix", "square", 2000, ["zidane", "garnet"], ["JRPG", "fantasy"]),
    ("final fantasy x", "square enix", 2001, ["tidus", "yuna"], ["JRPG", "fantasy"]),
    ("final fantasy xv", "square enix", 2016, ["noctis", "ignis"], ["action RPG", "fantasy"]),
    ("final fantasy xiv", "square enix", 2010, ["player"], ["MMORPG", "fantasy"]),
    ("persona 3", "atlus", 2006, ["protagonist", "mitsuru"], ["JRPG", "social sim"]),
    ("shenmue", "yu suzuki / sega", 1999, ["ryo hazuki"], ["adventure", "open world"]),
    ("shenmue ii", "sega", 2001, ["ryo hazuki"], ["adventure", "open world"]),
    ("yakuza 0", "ryo ga gotoku studio", 2015, ["kazuma kiryu", "majima"], ["action-adventure", "beat 'em up"]),
    ("yakuza: like a dragon", "ryo ga gotoku studio", 2020, ["ichiban kasuga"], ["RPG", "action-adventure"]),
    ("tekken 3", "bandai namco", 1997, ["jin kazama", "heihachi"], ["fighting"]),
    ("street fighter ii", "capcom", 1991, ["ryu", "ken", "chun-li"], ["fighting"]),
    ("street fighter v", "capcom", 2016, ["ryu", "chun-li"], ["fighting"]),
    ("mortal kombat 11", "netherrealm studios", 2019, ["scorpion", "raiden"], ["fighting"]),
    ("mortal kombat 1 (2011 reboot)", "netherrealm", 2011, ["scorpion"], ["fighting"]),  # clarify naming variant
    ("dragon ball fighterz", "arc system works", 2018, ["goku", "vegeta"], ["fighting"]),
    ("guilty gear -strive-", "arc system works", 2021, ["sol badguy"], ["fighting"]),
    ("soulcalibur ii", "namco", 2002, ["mitsurugi", "siegfried"], ["fighting"]),
    ("monster hunter generations", "capcom", 2015, ["hunter"], ["action RPG"]),
    ("splatoon 2", "nintendo", 2017, ["inkling"], ["shooter", "multiplayer"]),
    ("splatoon 3", "nintendo", 2022, ["inkling"], ["shooter", "multiplayer"]),
    ("no man's sky", "hello games", 2016, ["pilot"], ["space sim", "exploration"]),
    ("elite dangerous", "frontier developments", 2014, ["pilot"], ["space sim", "simulation"]),
    ("eve online", "ccp games", 2003, ["pilot"], ["MMO", "space sim"]),
    ("mass effect", "bioware", 2007, ["commander shepard", "liara"], ["action RPG", "sci-fi"]),
    ("mass effect 3", "bioware", 2012, ["commander shepard", "garrus"], ["action RPG", "sci-fi"]),
    ("dragon age: origins", "bioware", 2009, ["warden"], ["RPG", "fantasy"]),
    ("dragon age ii", "bioware", 2011, ["hawke"], ["RPG", "fantasy"]),
    ("dragon age: inquisition", "bioware", 2014, ["inquisitor"], ["RPG", "fantasy"]),
    ("planescape: torment", "black isle", 1999, ["the nameless one"], ["RPG"]),
    ("baldur's gate", "bio ware", 1998, ["player"], ["RPG"]),
    ("baldur's gate ii: shadows of amn", "bioware", 2000, ["player"], ["RPG"]),
    ("icewind dale", "black isle", 2000, ["player"], ["RPG"]),
    ("diablo", "blizzard north", 1996, ["rogue", "warrior"], ["action RPG", "dark fantasy"]),
    ("path of exile", "grinding gear games", 2013, ["exile"], ["action RPG", "online"]),
    ("grim dawn", "crate entertainment", 2016, ["inquisitor"], ["action RPG"]),
    ("gothic", "piranha bytes", 2001, ["player"], ["RPG"]),
    ("risen", "piranha bytes", 2009, ["player"], ["RPG", "fantasy"]),
    ("the witcher", "cd projekt red", 2007, ["geralt"], ["RPG", "fantasy"]),
    ("the witcher: enhanced edition", "cd projekt red", 2008, ["geralt"], ["RPG", "fantasy"]),
    ("the witcher 3: hearts of stone (expansion)", "cd projekt red", 2015, ["geralt"], ["action RPG"]),
    ("watch dogs", "ubisoft", 2014, ["aiden pearce"], ["action-adventure", "open world"]),
    ("watch dogs 2", "ubisoft", 2016, ["marcus holloway"], ["action-adventure", "open world"]),
    ("watch dogs: legion", "ubisoft", 2020, ["player"], ["action-adventure", "open world"]),
    ("forza horizon 4", "playground games", 2018, ["player"], ["racing", "open world"]),
    ("forza horizon 5", "playground games", 2021, ["player"], ["racing", "open world"]),
    ("forza motorsport", "turn 10", 2005, ["driver"], ["racing", "simulation"]),
    ("gran turismo 7", "polyphony digital", 2022, ["driver"], ["racing", "simulation"]),
    ("need for speed: underground", "ea black box", 2003, ["driver"], ["racing", "arcade"]),
    ("need for speed: most wanted", "criterion games", 2012, ["driver"], ["racing", "open world"]),
    ("for honor", "ubisoft", 2017, ["viking", "samurai"], ["action", "multiplayer"]),
    ("dying light", "techland", 2015, ["kyle crane"], ["survival horror", "parkour"]),
    ("dying light 2 stay human", "techland", 2022, ["aiden"], ["survival", "parkour"]),
    ("the division", "ubi massive", 2016, ["agent"], ["shooter", "MMO"]),
    ("the division 2", "ubi massive", 2019, ["agent"], ["shooter", "MMO"]),
    ("anthem", "bio ware", 2019, ["freelancer"], ["action RPG", "multiplayer"]),
    ("no more heroes", "grasshopper manufacture", 2007, ["travis touchdown"], ["action", "hack and slash"]),
    ("no more heroes 2", "grasshopper", 2010, ["travis"], ["action"]),
    ("katamari damacy", "namco", 2004, ["prince"], ["puzzle", "arcade"]),
    ("loop hero", "four quit", 2021, ["hero"], ["strategy", "roguelike"]),
    ("disco elysium", "za/um", 2019, ["harrier du bois"], ["RPG", "detective"]),
    ("the outer worlds", "obsidian entertainment", 2019, ["player"], ["RPG", "sci-fi"]),
    ("the outer wilds", "mobius digital", 2019, ["astronaut"], ["exploration", "adventure"]),
    ("outer wilds: echoes of the eye", "mobius digital", 2021, ["astronaut"], ["exploration", "adventure"]),
    ("the binding of isaac: rebirth", "edmund mcmillen", 2014, ["isaac"], ["roguelike", "action"]),
    ("warframe", "digital extremes", 2013, ["tenno"], ["action", "online"]),
    ("pathfinder: kingmaker", "owlcat games", 2018, ["player"], ["RPG", "strategy"]),
    ("baldur's gate 3", "larian studios", 2023, ["player", "laezel"], ["RPG", "party"]),
    ("divinity: original sin 2", "larian studios", 2017, ["player"], ["RPG", "party"]),
    ("divinity: original sin", "larian studios", 2014, ["player"], ["RPG"]),
    ("prey (2017)", "arkane studios", 2017, ["morgan yu"], ["first-person", "sci-fi"]),
    ("dishonored: death of the outsider", "arcane studios", 2017, ["billie lurk"], ["stealth", "action-adventure"]),
    ("prey (2006)", "human head studios", 2006, ["tommy"], ["first-person", "sci-fi"]),
    ("bioshock infinite: burial at sea (ep1)", "irrational games", 2013, ["booker", "elizabeth"], ["first-person shooter", "sci-fi"]),
    ("call of duty: wwii", "sledgehammer games", 2017, ["soldier"], ["first-person shooter", "historical"]),
    ("the forest", "endnight games", 2014, ["player"], ["survival", "horror"]),
    ("subnautica", "unknown worlds entertainment", 2018, ["player"], ["survival", "exploration"]),
    ("subnautica: below zero", "unknown worlds entertainment", 2021, ["player"], ["survival", "exploration"]),
    ("ark: survival evolved", "studio wildcard", 2015, ["survivor"], ["survival", "sandbox"]),
    ("rust", "facepunch studios", 2018, ["player"], ["survival", "multiplayer"]),
    ("seven: the days long gone", "imaginarium", 2017, ["bounty hunter"], ["RPG", "stealth"]),
    ("alan wake", "remedy entertainment", 2010, ["alan wake"], ["action-adventure", "psychological"]),
    ("control", "remedy entertainment", 2019, ["jessie fayden"], ["action-adventure", "sci-fi"]),
    ("max payne", "rockstar north", 2001, ["max payne"], ["third-person shooter", "noir"]),
    ("max payne 2: the fall of max payne", "remedy entertainment", 2003, ["max payne"], ["third-person shooter", "noir"]),
    ("quantum break", "remedy entertainment", 2016, ["jack joyce"], ["action-adventure", "sci-fi"]),
    ("alan wake 2", "remedy entertainment", 2023, ["alan wake"], ["survival horror", "psychological"]),
    ("the evil within", "tango gameworks", 2014, ["sebastian castellanos"], ["survival horror"]),
    ("the evil within 2", "tango gameworks", 2017, ["sebastian castellanos"], ["survival horror"]),
    ("persona 5 royal", "atlus", 2019, ["joker", "morgana"], ["JRPG", "social sim"]),
    ("shantae and the pirate's curse", "wayforward", 2014, ["shantae"], ["platformer", "metroidvania"]),
    ("shantae: half-genie hero", "wayforward", 2016, ["shantae"], ["platformer"]),
    ("metroidvania classics collection", "various", 2020, ["protagonists"], ["metroidvania"]),
    ("okami hd", "capcom", 2017, ["amaterasu"], ["action-adventure"]),
    ("soul reaver: legacy of kain", "crystal dynamics", 1999, ["raven"], ["action-adventure"]),
    ("legacy of kain: soul reaver 2", "crystal dynamics", 2001, ["raziel"], ["action-adventure"]),
    ("legacy of kain: defiance", "n/a", 2003, ["kain", "raziel"], ["action-adventure"]),
    ("system shock 2", "irrational games", 1999, ["player"], ["RPG", "sci-fi"]),
    ("sifu", "sloclap", 2022, ["yang"], ["action", "martial arts"]),
    ("forza horizon", "playground games", 2012, ["driver"], ["racing", "open world"]),
    ("gran turismo 3", "polyphony digital", 2001, ["driver"], ["racing"]),
    ("project cars 2", "slightly mad studios", 2017, ["driver"], ["racing", "simulation"]),
    ("assetto corsa", "kunos simulazioni", 2014, ["driver"], ["racing", "simulation"]),
    ("grid autosport", "codemasters", 2014, ["driver"], ["racing", "arcade"]),
    ("codemasters f1 2021", "codemasters", 2021, ["driver"], ["racing", "simulation"]),
    ("the king of fighters xiv", "snk", 2016, ["kyo", "iori"], ["fighting"]),
    ("persona 5 strikers", "omega force", 2020, ["joker", "morgana"], ["action RPG"]),
    ("yoshi's island", "nintendo", 1995, ["yoshi", "baby mario"], ["platformer"]),
    ("donkey kong country", "rare", 1994, ["donkey kong", "diddy"], ["platformer"]),
    ("donkey kong country: tropical freeze", "retro studios", 2014, ["donkey kong"], ["platformer"]),
    ("rayman legends", "ubisoft montpellier", 2013, ["rayman"], ["platformer"]),
    ("rayman origins", "ubisoft montpellier", 2011, ["rayman"], ["platformer"]),
    ("ico", "team ico", 2001, ["ico", "yorda"], ["adventure", "puzzle"]),
    ("limbo", "playdead", 2010, ["boy"], ["platformer", "puzzle"]),
    ("inside", "playdead", 2016, ["boy"], ["platformer", "puzzle"]),
    ("the witness", "jonathan blow", 2016, ["player"], ["puzzle", "exploration"]),
    ("fez", "polytron", 2012, ["fez"], ["puzzle", "indie"]),
    ("amanita designs: samorost 3", "amanita", 2016, ["gnome"], ["adventure", "puzzle"]),
    ("graceful explosion machine", "vertex pop", 2019, ["pilot"], ["shooter", "indie"]),
    ("hotline miami 2: wrong number", "devolver digital", 2015, ["player"], ["action", "top-down"]),
    ("bioshock infinite: columbia's stories", "irrational", 2013, ["booker", "elizabeth"], ["first-person shooter"]),
    ("the stanley parable", "galactic cafe", 2013, ["stanley"], ["interactive fiction", "indie"]),
    ("gone home", "the fullbright company", 2013, ["kate greenwood"], ["adventure", "walking sim"]),
    ("firewatch", "campo santo", 2016, ["henry"], ["adventure", "walking sim"]),
    ("what remains of edith finch", "giant sparrow", 2017, ["edith finch"], ["adventure", "walking sim"]),
    ("papers, please", "3909", 2013, ["inspector"], ["simulation", "puzzle"]),
    ("this war of mine", "11 bit studios", 2014, ["survivors"], ["survival", "strategy"]),
    ("frostpunk", "11 bit studios", 2018, ["leader"], ["strategy", "city builder"]),
    ("anno 1800", "blue byte", 2019, ["mayor"], ["strategy", "city builder"]),
    ("cities: skylines", "colossal order", 2015, ["mayor"], ["city builder", "simulation"]),
    ("simcity 4", "maxis", 2003, ["mayor"], ["city builder", "simulation"]),
    ("simcity (2013)", "maxis/ea", 2013, ["mayor"], ["city builder"]),
    ("civilization v", "firaxis games", 2010, ["leader"], ["strategy", "turn-based"]),
    ("civilization vi", "firaxis games", 2016, ["leader"], ["strategy", "turn-based"]),
    ("civilization iv", "firaxis games", 2005, ["leader"], ["strategy"]),
    ("age of empires ii", "ensemble studios", 1999, ["various leaders"], ["RTS", "historical"]),
    ("age of empires iv", "rel o games", 2021, ["various leaders"], ["RTS", "historical"]),
    ("age of mythology", "ensemble studios", 2002, ["heroes"], ["RTS", "mythology"]),
    ("total war: shogun 2", "creative assembly", 2011, ["daimyo"], ["strategy", "turn-based", "RTS"]),
    ("total war: warhammer ii", "creative assembly", 2017, ["lizardmen", "vampire counts"], ["strategy", "fantasy"]),
    ("hearts of iron iv", "paradox interactive", 2016, ["commander"], ["strategy", "grand strategy"]),
    ("stellaris", "paradox interactive", 2016, ["emperor"], ["strategy", "space 4x"]),
    ("crusader kings iii", "paradox interactive", 2020, ["dynasty"], ["strategy", "grand strategy"]),
    ("mount & blade: warband", "taleworlds", 2010, ["player"], ["RPG", "strategy"]),
    ("the witcher: wild hunt - gwent", "cd projekt red", 2016, ["player"], ["card game"]),
    ("gwent: the witcher card game", "cd projekt red", 2018, ["player"], ["card game", "multiplayer"]),
    ("magic: the gathering - arena", "wizards of the coast", 2019, ["player"], ["card game", "multiplayer"]),
    ("yu-gi-oh! duel links", "konami", 2016, ["player"], ["card game", "mobile"]),
    ("slay the spire", "mega crit games", 2019, ["the defect", "the silent"], ["deckbuilder", "roguelike"]),
    ("thronebreaker: the witcher tales", "cd projekt red", 2018, ["meve"], ["RPG", "card game"]),
    ("stonehearth", "radiant entertainment", 2015, ["settler"], ["simulation", "city builder"]),
    ("arkham horror: the card game", "fantasy flight", 2016, ["investigator"], ["card game", "co-op"]),
    ("darkest dungeon", "red hook studios", 2016, ["adventurer"], ["RPG", "roguelike"]),
    ("into the breach: crossfire", "subset games", 2018, ["pilot"], ["strategy"]),
    ("the long dark", "hinterland studio", 2014, ["will mackenzie"], ["survival"]),
    ("star wars battlefront ii (2005)", "pandemic studios", 2005, ["soldier"], ["action", "multiplayer"]),
    ("star wars battlefront ii (2017)", "ea dice", 2017, ["soldier"], ["action", "multiplayer"]),
    ("lego star wars: the force awakens", "travellers tales", 2016, ["rey", "bb-8"], ["family", "action"]),
    ("lego indiana jones", "travellers tales", 2008, ["indiana jones"], ["family", "action"]),
    ("lego indiana jones 2", "travellers tales", 2009, ["indiana jones"], ["family", "action"]),
    ("medieval ii: total war", "creative assembly", 2006, ["generals"], ["strategy"]),
    ("rome: total war", "creative assembly", 2004, ["generals"], ["strategy"]),
    ("rome: total war remastered", "creative assembly", 2021, ["generals"], ["strategy"]),
    ("civilization iii", "firaxis games", 2001, ["leader"], ["strategy"]),
    ("sid meier's pirates!", "firaxis", 2004, ["captain"], ["strategy", "action"]),
    ("the binding of isaac: afterbirth", "edmund mcmillen", 2015, ["isaac"], ["roguelike"]),
    ("the binding of isaac: wrath of the lamb", "edmund mcmillen", 2012, ["isaac"], ["roguelike"]),
    ("super smash bros. melee", "nintendo", 2001, ["mario", "link", "pikachu"], ["fighting", "party"]),
    ("super smash bros. ultimate", "nintendo", 2018, ["mario", "link", "pikachu", "sephiroth"], ["fighting", "party"]),
    ("ssb 64", "nintendo", 1999, ["mario", "link"], ["fighting", "party"]),
    ("pikmin", "nintendo", 2001, ["captain olimar"], ["strategy", "puzzle"]),
    ("pikmin 2", "nintendo", 2004, ["olimar"], ["strategy", "puzzle"]),
    ("pikmin 4", "nintendo", 2023, ["captain"], ["strategy", "puzzle"]),
    ("advance wars", "intelligent systems", 2001, ["commander"], ["strategy", "turn-based"]),
    ("fire emblem: path of radiance", "intelligent systems", 2005, ["ike"], ["strategy RPG"]),
    ("fire emblem: radiant dawn", "intelligent systems", 2007, ["ike"], ["strategy RPG"]),
    ("advance wars: dual strike", "intelligent systems", 2005, ["commanders"], ["strategy"]),
    ("lost odyssey", "mistwalker", 2007, ["kaim"], ["JRPG"]),
    ("blue dragon", "mistwalker", 2006, ["shu"], ["JRPG"]),
    ("tales of symphonia", "namco", 2003, ["lloyd", "genis"], ["JRPG"]),
    ("tales of berseria", "bandai namco", 2016, ["velvet"], ["JRPG"]),
    ("tales of arise", "bandai namco", 2021, ["alphen", "shionne"], ["JRPG"]),
    ("saga: frontiers", "square", 1997, ["various"], ["JRPG"]),
    ("star fox 64", "nintendo", 1997, ["fox mccloud"], ["shooter"]),
    ("star fox zero", "nintendo", 2016, ["fox mccloud"], ["shooter"]),
    ("starlink: battle for atlas", "ubisoft", 2018, ["pilot"], ["action", "space"]),
    ("no man's sky next", "hello games", 2018, ["pilot"], ["space sim", "exploration"]),
    ("rimworld", "ludeon studios", 2018, ["colonist"], ["simulation", "strategy"]),
    ("oxygen not included", "klei entertainment", 2019, ["duplicant"], ["simulation", "management"]),
    ("don't starve", "klei entertainment", 2013, ["wilson"], ["survival", "indie"]),
    ("don't starve together", "klei entertainment", 2016, ["wilson"], ["survival", "multiplayer"]),
    ("mark of the ninja", "klei entertainment", 2012, ["ninja"], ["stealth", "platformer"]),
    ("helldivers", "arrowhead game studios", 2015, ["soldier"], ["top-down shooter", "co-op"]),
    ("magicka", "arrowhead", 2011, ["mage"], ["action", "co-op"]),
    ("payday 2", "overkill software", 2013, ["heister"], ["heist", "co-op"]),
    ("payday: the heist", "overkill", 2011, ["heister"], ["heist", "co-op"]),
    ("the banner saga", "stoic", 2014, ["raven"], ["strategy", "RPG"]),
    ("banner saga 2", "stoic", 2016, ["raven"], ["strategy", "RPG"]),
    ("banner saga 3", "stoic", 2018, ["raven"], ["strategy", "RPG"]),
    ("dead space", "visceral games", 2008, ["isaac clarke"], ["survival horror", "sci-fi"]),
    ("dead space 2", "visceral games", 2011, ["isaac clarke"], ["survival horror", "sci-fi"]),
    ("dead space 3", "visceral games", 2013, ["isaac clarke"], ["survival horror", "action"]),
    ("alien: isolation", "creative assembly", 2014, ["amanda ripley"], ["survival horror", "sci-fi"]),
    ("system shock", "origin systems", 1994, ["player"], ["sci-fi", "RPG"]),
    ("vampire: the masquerade - bloodlines", "troika games", 2004, ["player"], ["RPG", "vampire"]),
    ("kingdom hearts", "square enix", 2002, ["sora", "donald", "goofy"], ["action RPG", "fantasy"]),
    ("kingdom hearts ii", "square enix", 2005, ["sora", "roxas"], ["action RPG", "fantasy"]),
    ("kingdom hearts iii", "square enix", 2019, ["sora", "riku"], ["action RPG", "fantasy"]),
    ("dark cloud", "level-5", 2000, ["max"], ["action RPG"]),
    ("dark cloud 2", "level-5", 2002, ["max"], ["action RPG"]),
    ("ni no kuni: wrath of the white witch", "level-5", 2011, ["oliver"], ["JRPG", "family"]),
    ("ni no kuni ii: revenant kingdom", "level-5", 2018, ["evan"], ["JRPG", "family"]),
    ("baba is you", "henriks", 2019, ["baba"], ["puzzle", "indie"]),
    ("hexcells infinite", "matthew brown", 2015, ["player"], ["puzzle"]),
    ("the talos principle", "croteam", 2014, ["player"], ["puzzle", "philosophical"]),
    ("satisfactory", "coffee stain studios", 2019, ["engineer"], ["simulation", "automation"]),
    ("goat simulator", "coffee stain studios", 2014, ["goat"], ["simulation", "sandbox"]),
    ("human fall flat", "no brakes games", 2016, ["bob"], ["physics", "puzzle"]),
    ("fall guys", "mediatonic", 2020, ["bean"], ["party", "battle royale"]),
    ("among us", "innersloth", 2018, ["crewmate", "impostor"], ["party", "social deduction"]),
    ("the witcher 3: blood and wine", "cd projekt red", 2016, ["geralt"], ["action RPG", "expansion"]),
    ("the witcher 3: hearts of stone", "cd projekt red", 2015, ["geralt"], ["action RPG", "expansion"]),
    ("dragon's dogma", "capcom", 2012, ["arisen"], ["action RPG"]),
    ("soulcalibur vi", "bandai namco", 2018, ["siegfried", "taki"], ["fighting"]),
    ("tekken 7", "bandai namco", 2015, ["jin kazama", "kazuya"], ["fighting"]),
    ("virtua fighter 5", "sega am2", 2006, ["akira"], ["fighting"]),
    ("project zero / fatal frame", "tecmokoei", 2001, ["miku"], ["survival horror", "photography"]),
    ("fatal frame ii: crimson butterfly", "tecmokoei", 2003, ["mio", "mayu"], ["survival horror"]),
    ("bioshock remastered", "2k", 2016, ["jack"], ["first-person shooter", "sci-fi"]),
    ("bioshock 2 remastered", "2k", 2016, ["subject delta"], ["first-person shooter", "sci-fi"]),
    ("soulslike anthology", "various", 2022, ["protagonists"], ["action RPG"]),
    ("minecraft dungeons", "mojang", 2020, ["hero"], ["dungeon crawler"]),
    ("minecraft: story mode", "telltale games", 2015, ["jesse"], ["adventure"]),
    ("telltale's the walking dead", "telltale games", 2012, ["lee everett", "clementine"], ["adventure", "episodic"]),
    ("telltale's the wolf among us", "telltale games", 2013, ["bigby wolf"], ["adventure"]),
    ("telltale's batman", "telltale games", 2016, ["bruce wayne"], ["adventure"]),
    ("telltale's guardians of the galaxy", "telltale games", 2017, ["star-lord"], ["adventure"]),
    ("the long dark: survival remains", "hinterland", 2020, ["will mackenzie"], ["survival"]),
    ("age of wonders iii", "triumph studios", 2014, ["ruler"], ["strategy", "fantasy"]),
    ("heroes of might and magic iii", "new world computing", 1999, ["heroes"], ["strategy", "turn-based"]),
    ("heroes of might and magic v", "nmanic", 2006, ["heroes"], ["strategy", "turn-based"]),
    ("magic the gathering: duels of the planeswalkers", "stainless games", 2009, ["player"], ["card game"]),
    ("mutant year zero: road to eden", "the beadles", 2018, ["stalker"], ["strategy", "RPG"]),
    ("vagrant story", "square", 2000, ["ashley riot"], ["action RPG"]),
    ("parasite eve", "square", 1998, ["aya brea"], ["RPG", "survival horror"]),
    ("parasite eve ii", "square", 1999, ["maya"], ["action", "survival horror"]),
    ("legacy of kain: blood omen", "silicon studios", 1996, ["kain"], ["action-adventure"]),
    ("sacred 2: fallen angel", "ascaron", 2008, ["hero"], ["action RPG"]),
    ("heroes of the storm", "blizzard entertainment", 2015, ["various heroes"], ["MOBA"]),
    ("dota 2", "valve", 2013, ["heroes"], ["MOBA"]),
    ("league of legends", "riot games", 2009, ["champions"], ["MOBA"]),
    ("smite", "hi-rez studios", 2014, ["gods"], ["MOBA"]),
    ("quake champions", "id software", 2017, ["champions"], ["first-person shooter", "arena"]),
    ("doom (1993)", "id software", 1993, ["doomguy"], ["first-person shooter"]),
    ("doom ii", "id software", 1994, ["doomguy"], ["first-person shooter"]),
    ("diablo iv", "blizzard entertainment", 2023, ["player"], ["action RPG"]),
    ("warhammer: vermintide 2", "fatshark", 2018, ["soldier"], ["co-op", "action"]),
    ("helldivers 2", "arrowhead studios", 2023, ["soldier"], ["co-op", "shooter"]),
    ("rimworld alpha", "ludeon studios", 2013, ["colonist"], ["simulation"]),
    ("papers please: inspector's edition", "3909", 2014, ["inspector"], ["simulation", "puzzle"]),
    ("spore", "maxis", 2008, ["creator"], ["simulation", "life sim"]),
    ("black & white", "lionhead studios", 2001, ["god"], ["simulation"]),
    ("rollercoaster tycoon", "chris sawyer", 1999, ["park manager"], ["simulation"]),
    ("rollercoaster tycoon 2", "chris sawyer", 2002, ["park manager"], ["simulation"]),
    ("rollercoaster tycoon 3", "frontier", 2004, ["park manager"], ["simulation"]),
    ("planet coaster", "frontier", 2016, ["park manager"], ["simulation"]),
    ("two brothers: a tale of two sons", "starbreeze", 2013, ["brothers"], ["adventure"]),
    ("yooka-laylee", "playtonic games", 2017, ["yooka", "laylee"], ["platformer"]),
    ("banjo-kazooie", "rare", 1998, ["banjo", "kazooie"], ["platformer"]),
    ("banjo-tooie", "rare", 2000, ["banjo", "kazooie"], ["platformer"]),
    ("conker's bad fur day", "rare", 2001, ["conker"], ["platformer", "mature"]),
    ("jet set radio", "sega", 2000, ["beat"], ["action", "parkour"]),
    ("jet set radio future", "sega", 2002, ["beat"], ["action"]),
    ("panzer dragoon", "sega", 1995, ["player"], ["rail shooter"]),
    ("shenmue iii", "ys net", 2019, ["ryo hazuki"], ["adventure", "open world"]),
    ("seiken densetsu 3", "square", 1995, ["party"], ["action RPG"]),
    ("secret of mana", "square", 1993, ["randi", "primm"], ["action RPG"]),
    ("trials fusion", "redlynx", 2014, ["rider"], ["racing", "platformer"]),
    ("trials rising", "uplay", 2019, ["rider"], ["racing", "platformer"]),
    ("mario & luigi: bowser's inside story", "alphadream", 2009, ["mario","luigi","bowser"], ["RPG", "adventure"]),
    ("paper mario: sticker star", "intelligent systems", 2012, ["mario"], ["RPG", "adventure"]),
    ("jackbox party pack", "jackbox games", 2014, ["players"], ["party", "multiplayer"]),
    ("jackbox party pack 2", "jackbox games", 2015, ["players"], ["party"]),
    ("jackbox party pack 7", "jackbox games", 2020, ["players"], ["party"]),
    ("humankind", "amplitude studios", 2021, ["leader"], ["strategy", "4x"]),
    ("endless legend", "amplitude studios", 2014, ["ruler"], ["strategy", "fantasy"]),
    ("endless space 2", "amplitude studios", 2017, ["commander"], ["strategy", "space"]),
    ("shadow tactics: blade of the shogun", "mimimi games", 2016, ["hayato"], ["strategy", "stealth"]),
    ("desperados iii", "mimimi games", 2020, ["cooper"], ["strategy", "stealth"]),
    ("commandos: behind enemy lines", "pyro studios", 1998, ["commandos"], ["strategy", "stealth"]),
    ("commandos 2: men of courage", "pyro studios", 2001, ["commandos"], ["strategy"]),
    ("tooth and tail", "pocketwatch games", 2017, ["commander"], ["RTS", "indie"]),
    ("age of empires iii", "ensemble studios", 2005, ["colonial leaders"], ["RTS", "historical"]),
    ("command & conquer: red alert 2", "westwood studios", 2000, ["soviet", "allied"], ["RTS"]),
    ("command & conquer 3: tiberium wars", "ea los angeles", 2007, ["general"], ["RTS"]),
    ("horizon zero dawn", "guerrilla games", 2017, ["aloy"], ["action RPG", "open world"]),
    ("horizon forbidden west", "guerrilla games", 2022, ["aloy"], ["action RPG", "open world"]),
    ("killzone", "guerrilla games", 2004, ["soldier"], ["first-person shooter"]),
    ("killzone 2", "guerrilla games", 2009, ["soldier"], ["first-person shooter"]),
    ("metal gear solid", "konami", 1998, ["solid snake", "liquid snake"], ["stealth", "action-adventure"]),
    ("metal gear solid 2: sons of liberty", "konami", 2001, ["raiden", "solid snake"], ["stealth"]),
    ("splinter cell", "ubisoft montreal", 2002, ["sam fisher"], ["stealth"]),
    ("splinter cell: blacklist", "ubisoft toronto", 2013, ["sam fisher"], ["stealth"]),
    ("thief: the dark project", "looking glass studios", 1998, ["garrett"], ["stealth", "first-person"]),
    ("thief 2: the metal age", "looking glass", 2000, ["garrett"], ["stealth"]),
    ("stalker: shadow of chernobyl", "gsc game world", 2007, ["stalker"], ["survival", "fps", "open world"]),
    ("s.t.a.l.k.e.r.: call of pripyat", "gsc game world", 2009, ["stalker"], ["survival", "open world"]),
    ("metro redux", "4a games", 2014, ["artem"], ["first-person shooter", "sci-fi"]),
    ("tomb raider (2013)", "core design/crystal dynamics", 2013, ["lara croft"], ["action-adventure"]),
    ("rise of the tomb raider", "crystal dynamics", 2015, ["lara croft"], ["action-adventure"]),
    ("shadow of the tomb raider", "eidos montreal", 2018, ["lara croft"], ["action-adventure"]),
    ("legacy of the void", "blizzard entertainment", 2015, ["jim raynor", "kerrigan"], ["RTS"]),
    ("star wars: the old republic", "bioware", 2011, ["player"], ["MMORPG", "sci-fi"]),
    ("everquest", "verant interactive", 1999, ["player"], ["MMORPG", "fantasy"]),
    ("world of warcraft", "blizzard entertainment", 2004, ["player"], ["MMORPG", "fantasy"]),
    ("world of warcraft: wrath of the lich king", "blizzard entertainment", 2008, ["arthas"], ["MMORPG", "fantasy"]),
    ("world of warcraft: legion", "blizzard entertainment", 2016, ["player"], ["MMORPG"]),
    ("guild wars 2", "arenanet", 2012, ["player"], ["MMORPG", "fantasy"]),
    ("tera", "bluehole", 2011, ["player"], ["MMORPG"]),
    ("blade & soul", "ncsoft", 2012, ["player"], ["MMORPG"]),
    ("runescape", "jagex", 2001, ["player"], ["MMORPG"]),
    ("old school runescape", "jagex", 2013, ["player"], ["MMORPG"]),
    ("diablo ii: resurrected", "blizzard entertainment", 2021, ["player"], ["action RPG", "remaster"]),
    ("persona 5 dancing in starlight", "atlus", 2018, ["joker", "morgana"], ["rhythm", "spin-off"]),
    ("project x zone", "bandai namco", 2012, ["crossover cast"], ["tactical RPG"]),
    ("project x zone 2", "bandai namco", 2015, ["crossover cast"], ["tactical RPG"]),
    ("advance wars: days of ruin", "intelligent systems", 2008, ["commanders"], ["strategy"]),
    ("mother 3", "brownie brown/nintendo", 2006, ["lucas"], ["JRPG", "cult classic"]),
    ("earthbound (mother 2)", "nintendo", 1994, ["ness", "paula"], ["RPG", "cult classic"]),
    ("mother", "nintendo", 1989, ["ninten"], ["RPG"]),
    ("undertale: deltarune chapter 1", "toby fox", 2018, ["kris", "susie"], ["RPG", "indie"]),
    ("doki doki literature club", "team salvage", 2017, ["sayori", "yuri", "natsuki", "monika"], ["visual novel", "psychological"]),
    ("ace attorney: phoenix wright", "capcom", 2001, ["phoenix wright"], ["visual novel", "puzzle"]),
    ("ace attorney: justice for all", "capcom", 2002, ["phoenix wright"], ["visual novel", "puzzle"]),
    ("ghost trick: phantom detective", "capcom", 2010, ["sissel"], ["puzzle", "adventure"]),
    ("zero escape: nine hours, nine persons, nine doors", "chunsoft", 2009, ["junpei"], ["visual novel", "puzzle"]),
    ("va-11 hall-a", "sukeban games", 2016, ["guy"], ["visual novel", "simulation"]),
    ("danganronpa: trigger happy havoc", "spike chunsoft", 2010, ["makoto"], ["visual novel", "mystery"]),
    ("danganronpa 2: goodbye despair", "spike chunsoft", 2012, ["hajime"], ["visual novel", "mystery"]),
    ("zero time dilemma", "chunsoft", 2016, ["player"], ["visual novel", "puzzle"]),
    ("ace attorney investigations: miles edgeworth", "capcom", 2009, ["miles edgeworth"], ["visual novel", "adventure"]),
    ("professor layton and the curious village", "level-5", 2007, ["professor layton", "luke"], ["puzzle", "adventure"]),
    ("professor layton and the diabolical box", "level-5", 2007, ["professor layton"], ["puzzle"]),
    ("phoenix wright: ace attorney - spirit of justice", "capcom", 2016, ["phoenix"], ["visual novel"]),
    ("far cry primal", "ubisoft", 2016, ["takkar"], ["action-adventure", "prehistoric"]),
    ("black desert online", "pearl abyss", 2015, ["player"], ["MMORPG"]),
    ("tera: the next saga", "bluehole", 2015, ["player"], ["MMORPG"]),
    ("blade & soul: revolution", "ncsoft", 2018, ["player"], ["MMORPG"]),
    ("the hunter: call of the wild", "expansive worlds", 2017, ["hunter"], ["simulation", "hunting"]),
    ("simcity 2000", "maxis", 1993, ["mayor"], ["city builder"]),
    ("sims medieval", "maxis", 2011, ["sim"], ["simulation", "RPG"]),
    ("the settlers", "blue byte", 1993, ["settler"], ["strategy", "city builder"]),
    ("the settlers 2", "blue byte", 1996, ["settler"], ["strategy"]),
    ("the settlers 7", "blue byte", 2010, ["settler"], ["strategy"]),
    ("tharsis", "choice pro games", 2016, ["astronauts"], ["strategy", "simulation"]),
    ("battle for middle-earth ii", "ea", 2006, ["armies"], ["RTS"]),
    ("lego harry potter: years 1-4", "travellers tales", 2010, ["harry"], ["family", "action"]),
    ("lego harry potter: years 5-7", "travellers tales", 2011, ["harry"], ["family", "action"]),
    ("lego worlds", "travellers tales", 2017, ["player"], ["sandbox", "creative"]),
    ("lego the hobbit", "travellers tales", 2012, ["bilbo"], ["family", "action"]),
    ("prince of persia: the sands of time", "ubisoft", 2003, ["prince"], ["action-adventure"]),
    ("prince of persia: warrior within", "ubisoft", 2004, ["prince"], ["action-adventure"]),
    ("prince of persia: the two thrones", "ubisoft", 2005, ["prince"], ["action-adventure"]),
    ("the incredible adventures of van helsing", "neocoregames", 2013, ["van helsing"], ["action RPG"]),
    ("torchlight", "runic games", 2009, ["player"], ["action RPG"]),
    ("torchlight ii", "runic games", 2012, ["player"], ["action RPG"]),
    ("torchlight iii", "echtra games", 2020, ["player"], ["action RPG"]),
    ("the secret world", "funcom", 2012, ["player"], ["MMORPG", "modern horror"]),
    ("anarchy online", "funcom", 2001, ["player"], ["MMORPG", "sci-fi"]),
    ("conan exiles", "funcom", 2018, ["survivor"], ["survival", "open world"]),
    ("darksiders", "vigil games", 2010, ["war", "death"], ["action-adventure"]),
    ("darksiders ii", "vigil games", 2012, ["death"], ["action-adventure"]),
    ("darksiders iii", "gunfire games", 2018, ["fury"], ["action-adventure"]),
    ("god eater", "bandai namco", 2010, ["protagonist"], ["action RPG"]),
    ("toukiden: kenzan", "omega force", 2013, ["slayer"], ["action RPG"]),
    ("soul sacrifice", "comcept", 2013, ["magusar"], ["action"]),
    ("dragons dogma dark arisen", "capcom", 2013, ["arisen"], ["action RPG"]),
    ("valkyria chronicles", "sega", 2008, ["welkin gunther"], ["strategy", "tactical RPG"]),
    ("valkyria chronicles 4", "sega", 2018, ["claude"], ["strategy", "tactical RPG"]),
    ("metal slug", "snk", 1996, ["soldier"], ["run and gun"]),
    ("metal slug 3", "snk", 2000, ["soldier"], ["run and gun"]),
    ("ace combat 7: skies unknown", "bandai namco", 2019, ["pilot"], ["flight", "simulation"]),
    ("ace combat 5: the unsung war", "namco", 2004, ["pilot"], ["flight", "simulation"]),
    ("ace combat zero: the belkan war", "namco", 2006, ["pilot"], ["flight", "simulation"]),
    ("star wars jedi: fallen order", "respawn entertainment", 2019, ["cal kestis"], ["action-adventure"]),
    ("star wars jedi: survivor", "respawn entertainment", 2023, ["cal kestis"], ["action-adventure"]),
    ("medievil", "sucker punch", 1998, ["sir dan"], ["action-adventure"]),
    ("medievil (remake)", "other ocean", 2019, ["sir dan"], ["action-adventure"]),
    ("bloodborne: the old hunters (dlc)", "fromsoftware", 2015, ["hunter"], ["action RPG", "dlc"]),
    ("shadowrun returns", "harebrained schemes", 2013, ["runner"], ["RPG", "cyberpunk"]),
    ("shadowrun: dragonfall", "harebrained schemes", 2014, ["runner"], ["RPG"]),
    ("shadowrun: hong kong", "harebrained schemes", 2015, ["runner"], ["RPG"]),
    ("vainglory", "super evil megacorp", 2014, ["hero"], ["MOBA", "mobile"]),
    ("realm royale", "heroic leap games", 2018, ["champion"], ["battle royale"]),
    ("paladins", "hi-rez studios", 2016, ["champion"], ["hero shooter"]),
    ("smash ultimate expansion", "nintendo", 2019, ["fighters"], ["fighting"]),
    ("soul calibur lost saga", "bandai namco", 2013, ["fighters"], ["fighting", "MMO"]),
    ("trine", "frozenbyte", 2009, ["wizard", "thief", "knight"], ["puzzle", "platformer"]),
    ("trine 2", "frozenbyte", 2011, ["wizard", "thief", "knight"], ["puzzle"]),
    ("trine 4: the nightmare prince", "frozenbyte", 2019, ["heroes"], ["puzzle"]),
    ("st reet fighter alpha 3", "capcom", 1998, ["ryu", "ken"], ["fighting"]),
    ("garou: mark of the wolves", "snk", 1999, ["rock"], ["fighting"]),
    ("samurai shodown", "snk", 1993, ["haohmaru"], ["fighting"]),
    ("the wonderful 101", "platinumgames", 2013, ["wonderful 100"], ["action"]),
    ("tunic", "isometric studio", 2022, ["fox"], ["action-adventure", "indie"]),
    ("gods will be watching", "deconstructeam", 2014, ["soldier"], ["pixel", "adventure"]),
    ("kings bounty: the legend", "katauri interactive", 2008, ["player"], ["strategy", "RPG"]),
    ("heroes of might and magic vii", "black hole entertainment", 2015, ["heroes"], ["strategy"]),
    ("mortal shell", "cold symmetry", 2020, ["hardened shell"], ["soulslike", "action"]),
    ("blasphemous", "the game kitchen", 2019, ["penitent one"], ["metroidvania", "action"]),
    ("hollow knight: silksong", "team cherry", 2023, ["hornet"], ["metroidvania", "platformer"]),
    ("ori and the blind forest", "moon studio", 2015, ["ori"], ["platformer", "metroidvania"]),
    ("ori and the will of the wisps", "moon studio", 2020, ["ori"], ["platformer", "metroidvania"]),
    ("the talos principle 2", "croteam", 2024, ["player"], ["puzzle"]),
    ("shadowrun trilogy", "various", 2020, ["runner"], ["RPG"]),
    ("breath of fire", "capcom", 1993, ["ragnar"], ["JRPG"]),
    ("breath of fire ii", "capcom", 1994, ["ragnar"], ["JRPG"]),
    ("soul reaver 2: defiled", "crystal dynamics", 2001, ["raziel"], ["action-adventure"]),
    ("journey", "thatgamecompany", 2012, ["roamer"], ["adventure", "indie"]),
    ("flower", "thatgamecompany", 2009, ["petal"], ["interactive", "indie"]),
    ("flOw", "thatgamecompany", 2006, ["organism"], ["indie"]),
    ("gods & monsters (immortals fenyx rising)", "ubisoft", 2020, ["fenyx"], ["action-adventure", "mythic"]),
    ("immortals fenyx rising", "ubisoft", 2020, ["fenyx"], ["action-adventure", "mythic"]),
    ("the last express", "christian loaf", 1997, ["robert cath"], ["adventure"]),
    ("myst", "cyan worlds", 1993, ["player"], ["adventure", "puzzle"]),
    ("riven", "cyan worlds", 1997, ["player"], ["adventure", "puzzle"]),
    ("obduction", "cyan worlds", 2016, ["player"], ["adventure", "puzzle"]),
    ("streets of rage 2", "sega", 1992, ["axel stone", "blaze"], ["beat 'em up"]),
    ("st reets of rage 4", "dotemu", 2020, ["axel"], ["beat 'em up"]),
    ("final fight", "capcom", 1989, ["hugo"], ["beat 'em up"]),
    ("castle crashers", "the behemoth", 2008, ["knight"], ["beat 'em up", "multiplayer"]),
    ("river city girls", "wayforward", 2019, ["kyoko", "misako"], ["beat 'em up", "indie"]),
    ("stardew valley: multiplayer update", "concernedape", 2017, ["farmer"], ["farming sim", "life sim"]),
    ("ark: survival of the fittest", "studio wildcard", 2016, ["player"], ["battle royale", "survival"]),
    ("ark: extinction", "studio wildcard", 2018, ["player"], ["survival", "expansion"]),
    ("ark: scorched earth", "studio wildcard", 2016, ["player"], ["survival", "expansion"]),
    ("hell let loose", "black matter", 2019, ["soldier"], ["first-person shooter", "historical"]),
    ("post scriptum", "periscope games", 2018, ["soldier"], ["first-person shooter", "historical"]),
    ("war thunder", "gaijin entertainment", 2013, ["pilot"], ["vehicle combat", "MMO"]),
    ("world of tanks", "wargaming", 2010, ["tank crew"], ["vehicle combat", "MMO"]),
    ("world of warships", "wargaming", 2015, ["crew"], ["vehicle combat", "MMO"]),
    ("armored core v", "fromsoftware", 2012, ["pilot"], ["mecha", "action"]),
    ("mechwarrior 5: mercenaries", "piranha bytes", 2019, ["pilot"], ["mecha", "simulation"]),
    ("bungie: destiny", "bungie", 2014, ["guardian"], ["shared-world shooter", "FPS"]),
    ("destiny 2", "bungie", 2017, ["guardian"], ["shared-world shooter", "FPS"]),
    ("halo: combat evolved", "bungie", 2001, ["master chief"], ["first-person shooter"]),
    ("halo 2", "bungie", 2004, ["master chief"], ["first-person shooter", "multiplayer"]),
    ("halo 3", "bungie", 2007, ["master chief"], ["first-person shooter"]),
    ("halo reach", "bungie", 2010, ["noble six"], ["first-person shooter"]),
    ("halo infinite", "343 industries", 2021, ["master chief"], ["first-person shooter", "open world"]),
    ("for honor: marching fire", "ubisoft", 2017, ["warrior"], ["action", "multiplayer"]),
    ("naruto to boruto: shinobi striker", "bandai namco", 2018, ["naruto"], ["fighting", "multiplayer"]),
    ("jump force", "bandai namco", 2019, ["manga characters"], ["fighting"]),
    ("one piece: pirate warriors 4", "omega force", 2020, ["luffy", "zoro"], ["action", "musou"]),
    ("warhammer 40k: dawn of war", "rel o", 2004, ["space marines"], ["RTS"]),
    ("warhammer 40k: space marine", "rel o", 2011, ["captain"], ["action", "third-person shooter"]),
    ("total war: warhammer", "creative assembly", 2016, ["lizardmen", "vampire counts"], ["strategy", "fantasy"]),
    ("total war: three kingdoms", "creative assembly", 2019, ["cao cao"], ["strategy", "historical"]),
    ("total war: rome remastered", "creative assembly", 2021, ["generals"], ["strategy"]),
    ("empire: total war", "creative assembly", 2009, ["generals"], ["strategy"]),
    ("company of heroes", "relic entertainment", 2006, ["soldiers"], ["RTS", "historical"]),
    ("company of heroes 2", "relic", 2013, ["soldiers"], ["RTS"]),
    ("homeworld", "rel ics", 1999, ["fleet commander"], ["RTS", "space"]),
    ("homeworld remastered collection", "gearbox", 2015, ["commander"], ["RTS", "space"]),
    ("gta: episodes from liberty city", "rockstar north", 2009, ["manny"], ["action-adventure"]),
    ("max payne 3", "rocksteady? (rockstar)", 2012, ["max payne"], ["third-person shooter"]),
    ("midnight club: los angeles", "rockstar north", 2008, ["driver"], ["racing"]),
    ("burnout paradise", "criterion games", 2008, ["driver"], ["racing", "arcade"]),
    ("burnout 3: takedown", "criterion games", 2004, ["driver"], ["racing", "arcade"]),
    ("split/second", "black rock studio", 2010, ["driver"], ["racing", "arcade"]),
    ("need for speed: shift", "slightly mad studios", 2009, ["driver"], ["racing", "simulation"]),
    ("grid", "codemasters", 2008, ["driver"], ["racing", "arcade"]),
    ("test drive unlimited", "eden games", 2006, ["driver"], ["racing", "open world"]),
    ("driver: san francisco", "reflexive entertainment", 2011, ["john Tanner"], ["racing", "action"]),
    ("driver 3", "reflexive", 2004, ["john Tanner"], ["racing", "action"]),
    ("the crew 2", "ivory tower", 2018, ["driver"], ["racing", "open world"]),
    ("forza horizon 2", "playground games", 2014, ["driver"], ["racing", "open world"]),
    ("motorstorm", "evolution studios", 2006, ["driver"], ["racing", "arcade"]),
    ("motorstorm: apocalypse", "evolution studios", 2011, ["driver"], ["racing", "arcade"]),
    ("project gotham racing 4", "bizarre creations", 2007, ["driver"], ["racing"]),
    ("need for speed: heat", "ghost games", 2019, ["driver"], ["racing", "open world"]),
    ("driver: parallel lines", "reflexive", 2006, ["john Tanner"], ["racing", "action"]),
    ("lego batman: the videogame", "travellers tales", 2008, ["batman", "robin"], ["family", "action"]),
    ("lego dimensions", "travellers tales", 2015, ["various"], ["family", "action"]),
    ("lego city undercover", "travellers tales", 2013, ["chase mcCain"], ["family", "open world"]),
    ("the crew", "ivory tower", 2014, ["driver"], ["racing", "open world"]),
    ("no more heroes 3", "grasshopper manufacture", 2021, ["travis"], ["action"]),
    ("trials hd", "redlynx", 2009, ["rider"], ["platformer", "racing"]),
    ("trials evolution", "redlynx", 2012, ["rider"], ["platformer", "racing"]),
    ("trials frontier", "ubi", 2014, ["rider"], ["platformer"]),
    ("uncharted: the lost legacy", "naughty dog", 2017, ["chloe frazer", "nadine ross"], ["action-adventure"]),
    ("the last of us remastered", "naughty dog", 2014, ["joel", "ellie"], ["action-adventure", "survival"]),
    ("the last of us part i (remake)", "naughty dog", 2022, ["ellie", "joel"], ["action-adventure", "survival"]),
    ("spore hero", "maxis", 2009, ["creator"], ["action", "adventure"]),
    ("gta online", "rockstar north", 2013, ["player"], ["multiplayer", "open world"]),
    ("vice city stories", "rockstar vienna", 2006, ["vic vance"], ["action-adventure"]),
    ("liberty city stories", "rockstar vienna", 2005, ["carlos"], ["action-adventure"]),
    ("manhunt", "rockstar north", 2003, ["james earle"], ["stealth", "horror"]),
    ("manhunt 2", "rockstar remastered", 2007, ["daniel lombardi"], ["stealth", "horror"]),
    ("red faction: guerrilla", "volition", 2009, ["axed worker"], ["action", "open world"]),
    ("red faction", "volition", 2001, ["dahl"], ["first-person shooter"]),
    ("red faction: armageddon", "volition", 2011, ["dahl"], ["third-person", "action"]),
    ("simple planes", "jundroo", 2015, ["pilot"], ["simulation", "sandbox"]),
    ("simple rockets", "jx2", 2013, ["engineer"], ["simulation", "space"]),
    ("kerbal space program", "squad", 2015, ["kerbal"], ["simulation", "space"]),
    ("kerbal space program 2", "intercept games", 2023, ["kerbal"], ["simulation", "space"]),
    ("warframe: the second dream", "digital extremes", 2013, ["tenno"], ["action", "sci-fi"]),
    ("warframe: plains of eidolon", "digital extremes", 2017, ["tenno"], ["open world", "action"]),
    ("crypto kitties", "dapper labs", 2017, ["cats"], ["blockchain", "collector"]),
    ("axie infinity", "sky mavis", 2018, ["axies"], ["blockchain", "strategy"]),
    ("myst remastered", "cyan worlds", 2021, ["player"], ["adventure", "puzzle"]),
]


