from typing import List, Tuple
#structure is (title, developer, year, [characters], [genres])

game_db: List[Tuple[str, str, int, List[str], List[str]]] = [
    ("the legend of zelda: breath of the wild", "nintendo", 2017, ["link", "zelda", "ganon"], ["action-adventure", "open world"]),
    ("the witcher 3: wild hunt", "cd projekt red", 2015, ["geralt", "yennefer", "triss"], ["action RPG", "open world"]),
    ("god of war", "santa monica studio", 2018, ["kratos", "atreus"], ["action-adventure", "hack and slash"]),
    ("hollow knight", "team cherry", 2017, ["knight", "hornet"], ["metroidvania", "platformer"]),
    ("elden ring", "fromsoftware", 2022, ["tarnished", "melina", "radahn"], ["action RPG", "open world"]),
    ("red dead redemption 2", "rockstar games", 2018, ["arthur morgan", "dutch", "john marston"], ["action-adventure", "open world"]),
    ("the last of us", "naughty dog", 2013, ["joel", "ellie"], ["action-adventure", "survival horror"]),
    ("cyberpunk 2077", "cd projekt red", 2020, ["v", "johnny silverhand"], ["action RPG", "open world"]),
    ("portal 2", "valve", 2011, ["chell", "glados", "wheatley"], ["puzzle-platformer", "sci-fi"]),
    ("minecraft", "mojang", 2011, ["steve", "alex"], ["sandbox", "survival", "creative"]),
    ("super mario odyssey", "nintendo", 2017, ["mario", "cappy", "bowser"], ["platformer", "adventure"]),
    ("metal gear solid v: the phantom pain", "konami", 2015, ["big boss", "quiet", "ocelot"], ["stealth", "action-adventure"]),
    ("persona 5", "atlus", 2016, ["joker", "morgana", "ann", "ryuji"], ["JRPG", "social simulation"]),
    ("bioshock infinite", "irrational games", 2013, ["booker dewitt", "elizabeth"], ["first-person shooter", "sci-fi"]),
    ("undertale", "toby fox", 2015, ["frisk", "sans", "papyrus", "toriel"], ["RPG", "indie"]),
    ("mass effect 2", "bioware", 2010, ["commander shepard", "garrus", "liara"], ["action RPG", "sci-fi"]),
    ("half-life 2", "valve", 2004, ["gordon freeman", "alyx vance"], ["first-person shooter", "sci-fi"]),
    ("doom eternal", "id software", 2020, ["doom slayer", "vega", "khan maykr"], ["first-person shooter", "action"]),
    ("final fantasy vii", "square enix", 1997, ["cloud", "tifa", "aerith", "sephiroth"], ["JRPG", "fantasy"]),
    ("stardew valley", "concernedape", 2016, ["farmer", "sebastian", "abigail", "penny"], ["farming sim", "life sim", "RPG"]),
    ("the legend of zelda: tears of the kingdom", "nintendo", 2023, ["link", "zelda", "ganondorf"], ["action-adventure", "open world"]),
    ("god of war ragnarok", "santa monica studio", 2022, ["kratos", "atreus", "freya"], ["action-adventure", "hack and slash"]),
    ("the last of us part ii", "naughty dog", 2020, ["ellie", "abby", "joel"], ["action-adventure", "survival horror"]),
    ("red dead redemption", "rockstar games", 2010, ["john marston", "bonnie mcfarlane"], ["action-adventure", "open world"]),
    ("the witcher 2: assassins of kings", "cd projekt red", 2011, ["geralt", "triss", "roche"], ["action RPG", "fantasy"]),
    ("dark souls iii", "fromsoftware", 2016, ["ashen one", "fire keeper", "lothric"], ["action RPG", "soulslike"]),
    ("metal gear solid 3: snake eater", "konami", 2004, ["naked snake", "the boss", "ocelot"], ["stealth", "action-adventure"]),
    ("bioshock", "irrational games", 2007, ["jack", "atlas", "andrew ryan"], ["first-person shooter", "sci-fi", "horror"]),
    ("persona 4", "atlus", 2008, ["yu narukami", "yosuke", "chie", "teddie"], ["JRPG", "social simulation"]),
    ("half-life: alyx", "valve", 2020, ["alyx vance", "russell"], ["first-person shooter", "VR", "sci-fi"]),
]

